project_id = "xtdnsisefrfngwmbcphy"

[functions.chat]
verify_jwt = false

[functions.group-chat-ai]
verify_jwt = false

[functions.moderate-message]
verify_jwt = false

[functions.classify-knowledge]
verify_jwt = false

[functions.vicen-admin]
verify_jwt = false
